import type { EmojiCategoryId, EmojiManifestEntry, EmojiTone } from "@lobby/shared";

function createEntry(
  category: Exclude<EmojiCategoryId, "recent">,
  emoji: string,
  label: string,
  keywords: string[],
  toneVariants?: Partial<Record<EmojiTone, string>>,
): EmojiManifestEntry {
  return {
    emoji,
    label,
    keywords,
    category,
    ...(toneVariants ? { toneVariants: toneVariants as Record<EmojiTone, string> } : {}),
  };
}

export const emojiManifestEntries: EmojiManifestEntry[] = [
  createEntry("smileys", "😀", "улыбка", ["смайл", "радость", "happy"]),
  createEntry("smileys", "😁", "улыбка с зубами", ["радость", "grin"]),
  createEntry("smileys", "😂", "слёзы радости", ["смех", "lol"]),
  createEntry("smileys", "🤣", "катаюсь от смеха", ["смех", "rofl"]),
  createEntry("smileys", "😊", "тёплая улыбка", ["милый", "nice"]),
  createEntry("smileys", "🙂", "лёгкая улыбка", ["ok", "normal"]),
  createEntry("smileys", "😉", "подмигивание", ["wink"]),
  createEntry("smileys", "😍", "влюблённость", ["love", "heart eyes"]),
  createEntry("smileys", "😘", "поцелуй", ["kiss"]),
  createEntry("smileys", "😎", "круто", ["cool"]),
  createEntry("smileys", "🥲", "улыбка со слезой", ["тепло", "эмоции"]),
  createEntry("smileys", "🤔", "задумался", ["think"]),
  createEntry("smileys", "🫡", "уважение", ["salute"]),
  createEntry("smileys", "😴", "сон", ["sleep"]),
  createEntry("smileys", "😭", "рыдаю", ["cry"]),
  createEntry("smileys", "😤", "фыркаю", ["anger", "steam"]),
  createEntry("smileys", "😡", "злость", ["angry"]),
  createEntry("smileys", "🤯", "взорвало мозг", ["mind blown"]),
  createEntry("smileys", "🥳", "праздник", ["party"]),
  createEntry("smileys", "🤡", "клоун", ["clown"]),
  createEntry(
    "people",
    "👍",
    "палец вверх",
    ["like", "ok"],
    {
      default: "👍",
      light: "👍🏻",
      "medium-light": "👍🏼",
      medium: "👍🏽",
      "medium-dark": "👍🏾",
      dark: "👍🏿",
    },
  ),
  createEntry(
    "people",
    "👎",
    "палец вниз",
    ["dislike"],
    {
      default: "👎",
      light: "👎🏻",
      "medium-light": "👎🏼",
      medium: "👎🏽",
      "medium-dark": "👎🏾",
      dark: "👎🏿",
    },
  ),
  createEntry(
    "people",
    "👏",
    "аплодисменты",
    ["clap"],
    {
      default: "👏",
      light: "👏🏻",
      "medium-light": "👏🏼",
      medium: "👏🏽",
      "medium-dark": "👏🏾",
      dark: "👏🏿",
    },
  ),
  createEntry(
    "people",
    "🙌",
    "ура",
    ["celebrate"],
    {
      default: "🙌",
      light: "🙌🏻",
      "medium-light": "🙌🏼",
      medium: "🙌🏽",
      "medium-dark": "🙌🏾",
      dark: "🙌🏿",
    },
  ),
  createEntry("people", "🤝", "рукопожатие", ["deal"]),
  createEntry(
    "people",
    "🙏",
    "спасибо",
    ["thanks", "please"],
    {
      default: "🙏",
      light: "🙏🏻",
      "medium-light": "🙏🏼",
      medium: "🙏🏽",
      "medium-dark": "🙏🏾",
      dark: "🙏🏿",
    },
  ),
  createEntry(
    "people",
    "🫶",
    "сердце руками",
    ["love"],
    {
      default: "🫶",
      light: "🫶🏻",
      "medium-light": "🫶🏼",
      medium: "🫶🏽",
      "medium-dark": "🫶🏾",
      dark: "🫶🏿",
    },
  ),
  createEntry("people", "💪", "сила", ["strong"]),
  createEntry("people", "👀", "смотрю", ["watch"]),
  createEntry("people", "🔥", "огонь", ["fire", "hot"]),
  createEntry("people", "🫠", "плыву", ["melt"]),
  createEntry("people", "🤌", "ну давай", ["gesture"]),
  createEntry("people", "✌️", "победа", ["peace"]),
  createEntry("people", "🤞", "скрестил пальцы", ["luck"]),
  createEntry("nature", "🌿", "ветка", ["leaf"]),
  createEntry("nature", "🌙", "луна", ["moon"]),
  createEntry("nature", "⭐", "звезда", ["star"]),
  createEntry("nature", "☀️", "солнце", ["sun"]),
  createEntry("nature", "🌧️", "дождь", ["rain"]),
  createEntry("nature", "❄️", "снег", ["snow"]),
  createEntry("nature", "🌊", "волна", ["wave"]),
  createEntry("nature", "🐈", "кот", ["cat"]),
  createEntry("nature", "🐶", "собака", ["dog"]),
  createEntry("nature", "🦊", "лиса", ["fox"]),
  createEntry("nature", "🐼", "панда", ["panda"]),
  createEntry("nature", "🦉", "сова", ["owl"]),
  createEntry("food", "☕", "кофе", ["coffee"]),
  createEntry("food", "🍵", "чай", ["tea"]),
  createEntry("food", "🥐", "круассан", ["breakfast"]),
  createEntry("food", "🍕", "пицца", ["pizza"]),
  createEntry("food", "🍔", "бургер", ["burger"]),
  createEntry("food", "🍜", "лапша", ["ramen"]),
  createEntry("food", "🍣", "суши", ["sushi"]),
  createEntry("food", "🍫", "шоколад", ["sweet"]),
  createEntry("food", "🍓", "клубника", ["berry"]),
  createEntry("food", "🍋", "лимон", ["lemon"]),
  createEntry("travel", "🏠", "дом", ["home"]),
  createEntry("travel", "🌆", "город", ["city"]),
  createEntry("travel", "✈️", "самолёт", ["plane"]),
  createEntry("travel", "🚗", "машина", ["car"]),
  createEntry("travel", "🚇", "метро", ["metro"]),
  createEntry("travel", "🗺️", "карта", ["map"]),
  createEntry("travel", "🧭", "компас", ["compass"]),
  createEntry("travel", "🏖️", "пляж", ["beach"]),
  createEntry("travel", "🏔️", "горы", ["mountain"]),
  createEntry("activity", "🎮", "игры", ["game"]),
  createEntry("activity", "🎧", "музыка", ["music"]),
  createEntry("activity", "🎬", "кино", ["movie"]),
  createEntry("activity", "📚", "книги", ["books"]),
  createEntry("activity", "⚽", "футбол", ["sport"]),
  createEntry("activity", "🏀", "баскетбол", ["sport"]),
  createEntry("activity", "🎯", "цель", ["target"]),
  createEntry("activity", "🧩", "пазл", ["puzzle"]),
  createEntry("activity", "🎉", "конфетти", ["party"]),
  createEntry("symbols", "❤️", "сердце", ["love", "heart"]),
  createEntry("symbols", "🖤", "чёрное сердце", ["heart"]),
  createEntry("symbols", "💔", "разбитое сердце", ["heartbreak"]),
  createEntry("symbols", "💯", "сто процентов", ["100"]),
  createEntry("symbols", "✨", "искры", ["sparkles"]),
  createEntry("symbols", "⚡", "молния", ["zap"]),
  createEntry("symbols", "✅", "готово", ["done", "check"]),
  createEntry("symbols", "❌", "крестик", ["no"]),
  createEntry("symbols", "❗", "важно", ["important"]),
  createEntry("symbols", "❓", "вопрос", ["question"]),
  createEntry("flags", "🇷🇺", "флаг россии", ["flag", "russia"]),
  createEntry("flags", "🇺🇸", "флаг сша", ["flag", "usa"]),
  createEntry("flags", "🇰🇿", "флаг казахстана", ["flag", "kazakhstan"]),
  createEntry("flags", "🇯🇵", "флаг японии", ["flag", "japan"]),
];
